/*
 * stop_wake_test.h
 *
 * Standalone STOP1 wake-up test helper for an STM32U5 EVM project.
 * Copy this file and stop_wake_test.c into a separate EVM CubeIDE project.
 */

#ifndef STOP_WAKE_TEST_H_
#define STOP_WAKE_TEST_H_

#include "main.h"

/*
 * Set these four macros to match the EVM project pin names generated by CubeMX.
 * The wake pin must be configured as GPIO_EXTI in CubeMX.
 */
#define STOP_WAKE_LED_GPIO_Port GPIOA
#define STOP_WAKE_LED_Pin       GPIO_PIN_5
#define STOP_WAKE_EXTI_Pin      GPIO_PIN_13

void StopWakeTest_Init(void);
void StopWakeTest_RunOnce(void);
void StopWakeTest_OnExti(uint16_t GPIO_Pin);

#endif /* STOP_WAKE_TEST_H_ */
